# Generated by Django 5.0.6 on 2024-05-29 09:09

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("polls", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="question",
            name="pub_date",
        ),
        migrations.RemoveField(
            model_name="question",
            name="question_text",
        ),
    ]
